# 配置文件请严格遵循yaml语法格式，yaml学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 定时时间
alarm_timed: '18:22'

# 格言渠道
# 1 : ONE●一个
# 2 : 词霸（每日英语，双语）
# 3 : 土味情话
dictum_channel: 2
#图灵key
tuling_key:
-
    '52e1fe64f1e645caa17828a4be35d8d5'
-
    '8edce3ce905a4c1dbb965e6b35c3834d'
-
    'eb720a8970964f3f855d863d24406576'
-
    '1107d5601866433dba9599fac1bc0083'
-
    '71f28bf79c820df10d39b4074345ef8c'

# 是否开启自动回复限制  1:对指定好友开启自动回复,2:对所有好友开启自动回复
open_reply_limit: 2

auto_reply_list:
# 请填写好友的微信昵称
-
    '动霸tua'

-
    '刚把得'

girlfriend_infos:
-
    #女友微信昵称
    wechat_name: 'filehelper'
    #女友所在城市
    city_name: '成都'
    # 从那天开始勾搭的（可空）
    start_date: '2012-12-9'
    # 短句的最后留言（可空）
    sweet_words: '来自最爱你的我。'

    #如果你有多个人需要发送，则参照这个样式，复制即可
    #如不需要，则删除或注解下面所有的数据
    # wechat_name: '陈老师'
    # city_name: '朝阳区'
    # start_date: '2018-11-11'
    # sweet_words: '来自你俊美的老公。'
